name: 'Keycloak Realm Configuration'
description: 'Imports a keycloak realm config'
inputs:
  url:  # id of input
    description: 'URL of a Keycloak server'
    required: true
  username:
    description: 'Username used to import config'
    required: true
  password:
    description: 'Password used to import config'
    required: true
  login-realm:
    description: 'Realm used to log in'
    required: false
    default: 'master'
  path:
    description: 'Location of config files (if location is a directory, all files will be imported)'
    required: false
    default: '/config'
  force:
    description: 'Import realm even if config file is unchanged'
    required: false
    default: false
  availability-check-enabled:
    description: 'Wait until Keycloak is available'
    required: false
    default: false
  availability-check-timeout:
    description: 'Wait timeout for keycloak availability check'
    required: false
    default: '120s'
    
runs:
  using: 'docker'
  image: 'docker://adorsys/keycloak-config-cli:latest-18.0.0'
  args:
    - '--keycloak.url=${{ inputs.url }}'
    - '--keycloak.user=${{ inputs.username }}'
    - '--keycloak.password=${{ inputs.password }}'
    - '--keycloak.login-realm=${{ inputs.login-realm }}'
    - '--import.path=${{ inputs.path }}'
    - '--import.force=${{ inputs.force }}'
    - '--keycloak.availability-check.enabled=${{ inputs.availability-check-enabled }}'
    - '--keycloak.availability-check.timeout=${{ inputs.availability-check-timeout }}'
